import type { NextConfig } from "next";

/**
 * The five course URLs that existed before 8 Aug 2026, and only those five.
 *
 * `/courses/gtm` through `/courses/starter` were the routes until the segment
 * became the course title. Those URLs are in the wild — the homepage hero linked
 * `/courses/gtm#curriculum`, the footer listed all five, and anything shared or
 * crawled before the change points at them.
 *
 * ------------------------------------------------- why this is written out now
 *
 * It used to be generated by importing `courses` from content.ts and mapping it.
 * The catalogue lives in Postgres now, and this list must not follow it there:
 * `next.config.ts` is evaluated before the app has a request context, and making
 * the build depend on a live database to answer "what redirects exist" trades a
 * deploy-time failure mode for a runtime one.
 *
 * It also should not follow it. This is not a view of the current catalogue — it
 * is a record of five addresses that were once real and must keep resolving.
 * That set is closed and cannot grow: a course created in the console today
 * never had a `/courses/<id>` URL, so it needs no entry here. Deleting a course
 * does not remove its entry either, because the old address is still in the
 * wild.
 *
 * `permanent: true` — a 308, the correct code for a URL that has moved for good
 * and the one that transfers the old address's accumulated signals to the new
 * one. A 307 would leave the old URL as the one a crawler keeps re-checking.
 */
const LEGACY_COURSE_IDS: readonly (readonly [string, string])[] = [
  ["gtm", "applied-ai-for-gtm-teams"],
  ["media", "applied-ai-for-video-and-media"],
  ["literacy", "ai-literacy-ethics-and-data-compliance"],
  ["infra", "applied-ai-infrastructure"],
  ["starter", "ai-starter-for-small-business"],
];

const nextConfig: NextConfig = {
  async redirects() {
    return [
      ...LEGACY_COURSE_IDS.map(([id, slug]) => ({
        source: `/courses/${id}`,
        destination: `/courses/${slug}`,
        permanent: true,
      })),
      /*
        /admin/seats became /admin/judging on 9 Aug.

        The old page showed one of the three things being a judge is made of and
        called that "Judge seats", which is why Roan read it as confusing — the
        page's own name was a description of the fragment it showed. The new
        route carries all three; the note at the head of that file has the
        reasoning.

        `permanent: false`, and it is the one entry here that is. The list above
        is public URLs that were once indexed and must transfer their signals;
        this is an admin route that nothing outside the console links to and
        that is `robots: noindex` anyway. A 307 keeps a bookmark working without
        asking a browser to cache the rule forever.
      */
      { source: "/admin/seats", destination: "/admin/judging", permanent: false },
    ];
  },

  // The dev overlay badge sits on top of the closing CTA in review captures.
  devIndicators: false,
  experimental: {
    /*
      The client components import icons from the `@phosphor-icons/react`
      barrel, which re-exports roughly 1,200 components. Server components use
      the `/dist/ssr` entry and are unaffected, but a barrel import in a client
      bundle pulls the whole index in before tree-shaking gets a look at it.
      This rewrites those to per-icon paths at build time.
    */
    optimizePackageImports: ["@phosphor-icons/react"],
  },
  images: {
    // Placeholder photography only. Remove once real assets land in /public
    // or a media host. See IMAGE_MANIFEST in src/lib/content.ts.
    remotePatterns: [{ protocol: "https", hostname: "picsum.photos" }],
  },

  /**
   * Security headers.
   *
   * There were none until lessons could embed things. Now that a lesson can
   * carry a YouTube player and a third-party interactive tool, `frame-src` is
   * the difference between "an author picked from a reviewed list" and "any
   * origin that ends up in a jsonb column can execute script in our page".
   *
   * ---------------------------------------------- this list exists twice, deliberately
   *
   * The same origins are written into the CHECK constraint on
   * `lesson_blocks.payload` for `kind = 'embed'`. That is not duplication to
   * remove — it is defence at both ends: the constraint means a bad origin
   * cannot be *stored*, and this means a bad origin cannot be *loaded* even if
   * one somehow were. They must be edited in the same commit, and the migration
   * says so too.
   *
   * ------------------------------------------------------------- no script-src
   *
   * On purpose. A real `script-src` fights Next's inline bootstrap unless nonces
   * are threaded through the whole render, and a CSP that has to be loosened
   * every time something breaks teaches everyone to loosen it. A small correct
   * policy beats a large one nobody trusts. `script-src` lands with nonces, as
   * its own change.
   */
  async headers() {
    const csp = [
      "frame-src 'self' https://www.youtube-nocookie.com https://www.figma.com https://colab.research.google.com https://codesandbox.io https://www.desmos.com https://www.loom.com",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; ");

    return [
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          /* The site asks for none of these anywhere, and saying so stops an
             embedded third party asking on our behalf. */
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
};

export default nextConfig;
