import type { NextConfig } from "next";

/**
 * The five course URLs that existed before 8 Aug 2026, and only those five.
 *
 * `/courses/gtm` through `/courses/starter` were the routes until the segment
 * became the course title. Those URLs are in the wild — the homepage hero linked
 * `/courses/gtm#curriculum`, the footer listed all five, and anything shared or
 * crawled before the change points at them.
 *
 * ------------------------------------------------- why this is written out now
 *
 * It used to be generated by importing `courses` from content.ts and mapping it.
 * The catalogue lives in Postgres now, and this list must not follow it there:
 * `next.config.ts` is evaluated before the app has a request context, and making
 * the build depend on a live database to answer "what redirects exist" trades a
 * deploy-time failure mode for a runtime one.
 *
 * It also should not follow it. This is not a view of the current catalogue — it
 * is a record of five addresses that were once real and must keep resolving.
 * That set is closed and cannot grow: a course created in the console today
 * never had a `/courses/<id>` URL, so it needs no entry here. Deleting a course
 * does not remove its entry either, because the old address is still in the
 * wild.
 *
 * `permanent: true` — a 308, the correct code for a URL that has moved for good
 * and the one that transfers the old address's accumulated signals to the new
 * one. A 307 would leave the old URL as the one a crawler keeps re-checking.
 */
const LEGACY_COURSE_IDS: readonly (readonly [string, string])[] = [
  ["gtm", "applied-ai-for-go-to-market"],
  ["media", "hybrid-filmmaking"],
  ["literacy", "ai-education-ethics-and-data-compliance"],
  ["infra", "applied-ai-infrastructure-fundamentals"],
  ["starter", "ai-starter-for-small-business"],
];

/**
 * The four slugs that were real between 8 and 11 Aug 2026.
 *
 * The curriculum moved to the blueprint on 11 Aug and four of the five titles
 * changed with it, which changed four slugs: a course called Hybrid filmmaking
 * cannot live at /courses/applied-ai-for-video-and-media, and a URL that
 * describes a different course is worse than an ugly one.
 *
 * Same reasoning as the list above, and the same closed set: these addresses
 * were live, they are in the wild, and they keep resolving. A slug that changes
 * again adds a row here rather than editing one, because the row that is edited
 * is the one that stops working.
 */
const RENAMED_COURSE_SLUGS: readonly (readonly [string, string])[] = [
  ["applied-ai-for-gtm-teams", "applied-ai-for-go-to-market"],
  ["applied-ai-for-video-and-media", "hybrid-filmmaking"],
  ["ai-literacy-ethics-and-data-compliance", "ai-education-ethics-and-data-compliance"],
  ["applied-ai-infrastructure", "applied-ai-infrastructure-fundamentals"],
];

const nextConfig: NextConfig = {
  async redirects() {
    return [
      ...LEGACY_COURSE_IDS.map(([id, slug]) => ({
        source: `/courses/${id}`,
        destination: `/courses/${slug}`,
        permanent: true,
      })),
      /*
        The renamed slugs carry their sub-paths with them, which the id list
        above does not need to: `/courses/<slug>/start` is a real route, and an
        exact-path rule would 404 the one link that begins an enrolment.
      */
      ...RENAMED_COURSE_SLUGS.flatMap(([from, to]) => [
        { source: `/courses/${from}`, destination: `/courses/${to}`, permanent: true },
        { source: `/courses/${from}/:path*`, destination: `/courses/${to}/:path*`, permanent: true },
        /*
          The reader lands on the course rather than on the old lesson. Every
          lesson slug changed with the curriculum, so carrying `:path*` through
          would trade a redirect for a 404 one hop later.
        */
        { source: `/learn/${from}/:path*`, destination: `/learn/${to}`, permanent: true },
        { source: `/learn/${from}`, destination: `/learn/${to}`, permanent: true },
      ]),
      /*
        /admin/seats became /admin/judging on 9 Aug.

        The old page showed one of the three things being a judge is made of and
        called that "Judge seats", which is why Roan read it as confusing — the
        page's own name was a description of the fragment it showed. The new
        route carries all three; the note at the head of that file has the
        reasoning.

        `permanent: false`, and it is the one entry here that is. The list above
        is public URLs that were once indexed and must transfer their signals;
        this is an admin route that nothing outside the console links to and
        that is `robots: noindex` anyway. A 307 keeps a bookmark working without
        asking a browser to cache the rule forever.
      */
      { source: "/admin/seats", destination: "/admin/judging", permanent: false },
    ];
  },

  // The dev overlay badge sits on top of the closing CTA in review captures.
  devIndicators: false,
  experimental: {
    /*
      The client components import icons from the `@phosphor-icons/react`
      barrel, which re-exports roughly 1,200 components. Server components use
      the `/dist/ssr` entry and are unaffected, but a barrel import in a client
      bundle pulls the whole index in before tree-shaking gets a look at it.
      This rewrites those to per-icon paths at build time.
    */
    optimizePackageImports: ["@phosphor-icons/react"],
  },
  images: {
    // Placeholder photography only. Remove once real assets land in /public
    // or a media host. See IMAGE_MANIFEST in src/lib/content.ts.
    remotePatterns: [
      { protocol: "https", hostname: "picsum.photos" },
      /*
        Supabase Storage, for roster portraits and employer marks uploaded in the
        console rather than committed to /public.
        
        Scoped to the storage object path rather than the whole host, so this
        entry cannot be used to proxy something else on the project's domain
        through the image optimiser.

        The hostname is derived from the project URL rather than written out, so
        a project move is one environment variable rather than a code change —
        and so this file cannot disagree with the client the rest of the app
        builds. `next.config.ts` runs in Node at build and start, so reading the
        env var here is legitimate in a way it would not be in a component.
      */
      {
        protocol: "https",
        hostname: new URL(
          process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://localhost",
        ).hostname,
        pathname: "/storage/v1/object/public/**",
      },
    ],
  },

  /**
   * Security headers.
   *
   * There were none until lessons could embed things. Now that a lesson can
   * carry a YouTube player and a third-party interactive tool, `frame-src` is
   * the difference between "an author picked from a reviewed list" and "any
   * origin that ends up in a jsonb column can execute script in our page".
   *
   * ---------------------------------------------- this list exists twice, deliberately
   *
   * The same origins are written into the CHECK constraint on
   * `lesson_blocks.payload` for `kind = 'embed'`. That is not duplication to
   * remove — it is defence at both ends: the constraint means a bad origin
   * cannot be *stored*, and this means a bad origin cannot be *loaded* even if
   * one somehow were. They must be edited in the same commit, and the migration
   * says so too.
   *
   * ------------------------------------------------------------- no script-src
   *
   * On purpose. A real `script-src` fights Next's inline bootstrap unless nonces
   * are threaded through the whole render, and a CSP that has to be loosened
   * every time something breaks teaches everyone to loosen it. A small correct
   * policy beats a large one nobody trusts. `script-src` lands with nonces, as
   * its own change.
   */
  async headers() {
    const csp = [
      "frame-src 'self' https://www.youtube-nocookie.com https://www.figma.com https://colab.research.google.com https://codesandbox.io https://www.desmos.com https://www.loom.com",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; ");

    return [
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          /* The site asks for none of these anywhere, and saying so stops an
             embedded third party asking on our behalf. */
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
};

export default nextConfig;
